In [8]:
# 1.导包
import numpy as np
print("success")

success


|# 1.Numpy属性介绍


In [9]:
# numpy -> 和数学操作相关的库，numpy的数组是多维的，并且是固定类型的，numpy的数组是ndarray类型，主要用于：矩阵运算
# 1.创建numpy的ndarray对象
arr1 = np.arange(15).reshape(3, 5)
print(arr1)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


# 2.演示numpy的常用属性